---

- name: Create secret resource containing team AWS credentials
  become_user: "{{ k8s_user }}"
  delegate_to: 127.0.0.1
  k8s:
    state: present
    context: "{{ k8s_context }}"
    definition: "{{ lookup('template', 'team_awscredentials_secret.yml') }}"
  loop: "{{ query('dict', external_secrets_aws_access) }}"