---

- name: Create secret resource containing team AWS credentials
  become_user: "{{ k8s_user }}"
  delegate_to: 127.0.0.1
  k8s:
    state: present
    definition: "{{ lookup('template', 'team_awscredentails_secret.yml') }}"
  loop: "{{ query('dict', external_secrets_aws_access) }}"