---

- name: Create clustersecretstore resource referencing the team aws credentials secret 
  become_user: "{{ k8s_user }}"
  delegate_to: 127.0.0.1
  k8s:
    state: present
    context: "{{ k8s_context }}"
    definition: "{{ lookup('template', 'team_clustersecretstore.yml') }}"
  loop: "{{ query('dict', external_secrets_aws_access) }}"