---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ item.key }}-clustersecretstore
spec:
  provider:
    aws:
      service: "ParameterStore"
      region: "us-west-2"
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: {{ item.key }}-awsaccess-secret
            namespace: "external-secerts"
          secretAccessKeySecretRef:
            key: secret-access-key
            name: {{ item.key }}-awsaccess-secret
            namespace: "external-secerts"