---
apiVersion: v1
kind: Secret
metadata:
  name: {{ item.key }}-awsaccess-secret
  namespace: external-secrets
type: Opaque
data:
  access-key: {{ item.value.aws_access_key_b64 }}
  secret-access-key: {{ item.value.aws_secret_access_key_b64 }}
